# starship configuration: https://starship.rs/config/
command_timeout = 5000

[nodejs]
format = "via [node.js ($version )]($style)"

[python]
python_binary = "python3"

[shell]
bash_indicator = "bash "
zsh_indicator = ""
unknown_indicator = "??? "
style = "cyan bold"
format = "[$indicator]($style)"
disabled = false
